# Generated by Django 4.2.15 on 2024-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0),
        ),
    ]
